[build]
  base = "abc-frontend"  # Pasta do frontend
  publish = "build"      # Pasta de build do React (dentro de abc-frontend)
  functions = "netlify/functions"  # Pasta das funções serverless

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200